### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by rpicard** [rpicard/explore-flask#35]
**Grammar**

Plan to write a static analysis script to check for these things once I've decided on the best choice for grammar.
- [x] Decide on contractions (it's, we'll, I'll, you'll)

**Front matter**
- [ ] Thank the people who need thanking
- [x] Update release notes

**Formatting**
- [x] Note boxes
- [x] File names should be italics
- [x] Interesting terms should be bold
- [x] Listings should be formatted in appropriate boxes
- [x] References (internal and external) should be checked

**Kickstarter**
- [ ] Mail postcards
- [ ] Mail stickers
- [ ] Mail print books at 1.0
- [ ] List names of $50+ backers
- [ ] Encode $100+ backers
- [ ] Balanced logo
